app = 'api-spell-jan-czechowski-com'
primary_region = 'fra'

[http_service]
  internal_port = 8000
  force_https = false
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

[build]
  dockerfile = 'Dockerfile'
  context = '..'

[[vm]]
  memory = '2048mb'
  cpus = 1
